name: "web_app"
mode: "dev"
port: 8090
version: "v1.2.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7


mysql:
  host: "106.54.119.58"
  port: 3306
  user: "root"
  password: "******"
  dbname: "bluebell"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "106.54.119.58"
  password: "*****"
  port: "6379"
  dbname: 0
  pool_size: 100

